on:
  workflow_dispatch:
    inputs:
      deploy_all:
        type: boolean
        description: "Deploy everything"
        default: false
      deploy_keyvault:
        type: boolean
        description: "Deploy Key Vault"
        default: false
      deploy_storage:
        type: boolean
        description: "Deploy Storage Account"
        default: false
      deploy_vnet:
        type: boolean
        description: "Deploy VNet"
        default: false

jobs:
  deploy_keyvault:
    if: inputs.deploy_all == true || inputs.deploy_keyvault == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying Key Vault"

  deploy_storage:
    if: inputs.deploy_all == true || inputs.deploy_storage == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying Storage Account"

  deploy_vnet:
    if: inputs.deploy_all == true || inputs.deploy_vnet == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying VNet"
